version: '3.7'
services:
  backend_app:
    volumes:
      - :/home/node/app
    ports:
      - 3000:3000
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "npm i && npx sequelize-cli db:migrate && npm run start"
    restart: on-failure
    depends_on:
      - mysql
    networks:
      - motobyo-network

  mysql:
      image: mysql:8.0.19
      restart: always
      command: --default-authentication-plugin=mysql_native_password --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
      environment:
        MYSQL_DATABASE: ${DB_DATABASE_NAME}
        MYSQL_USER: ${DB_USER_NAME}
        MYSQL_PASSWORD: ${DB_USER_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      ports:
        - 3306:3306
      expose:
        - 3306
      volumes:
        - ./docker/mysql8:/docker-entrypoint-initdb.d
        - ./docker/mysql8/data:/var/lib/mysql
      networks:
        motobyo-network:
          aliases:
          - mysql
networks:
  motobyo-network:
    driver: bridge
