version: "3.7"
services:
  app:
    image: node:10.22-alpine
    command: sh -c "npm i && npx sequelize-cli db:migrate && npm start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      databaseUsername: ${databaseUsername}
      databasePassword: ${databasePassword}
      databaseName: ${databaseName}
      tokenSecret: ${tokenSecret}
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
    - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${databasePassword}
      MYSQL_DATABASE: ${databaseName}
volumes:
  todo-mysql-data:
